### ISSUE TITLE
Small typo in the article :)

### ISSUE THREAD

**Issue by delphaber** [jmeinerz/rebasing-hook#2]
![CleanShot 2020-05-04 at 12 03 28@2x](https://user-images.githubusercontent.com/139284/80955298-562a2180-8dff-11ea-91fb-e2278a6f921e.png)

**Comment by jmeinerz** [comment]
Nice catch! Thanks a lot 👍

**Comment by jmeinerz** [comment]
[Updated!](https://thoughtbot.com/blog/confirm-your-changes-at-the-end-of-a-git-rebase)

Thank you :)
